name: Destroy EC2 Instance

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
                            -backend-config="key=terraform.tfstate" \
                            -backend-config="region=${{ secrets.AWS_REGION }}" \
                            -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE_NAME }}"

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
